# NVIDIA API Configuration

# API URL including rtx 50 series availability information and direct purchase links
url = "https://api.nvidia.partners/edge/product/search?page=1&limit=9&manufacturer_filter=NVIDIA%7E1&category=GPU&locale=de-de&manufacturer=NVIDIA"

# Request settings
[request]
timeout_secs = 30 # API request timeout in seconds
connect_timeout_secs = 15 # API connection timeout in seconds
max_attempts = 4 # max number of attempts to make the request
sleep_ms_min = 500 # min time between requests in ms
sleep_ms_max = 1000 # max time between requests in ms

# Browser emulation headers
[headers]
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
accept = "application/json, text/plain, */*"
accept_language = "en-US,en;q=0.9,de;q=0.8"
connection = "keep-alive"
cache_control = "no-cache"
pragma = "no-cache"
sec_fetch_dest = "empty"
sec_fetch_mode = "cors"
sec_fetch_site = "cross-site"
origin = "https://www.nvidia.com"
referer = "https://www.nvidia.com/"
sec_ch_ua = "\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\""
sec_ch_ua_mobile = "?0"
sec_ch_ua_platform = "\"Windows\""

# Default purchase links (when these change, the product_checker will mark the product as available)
[default_links]
rtx_5080 = "https://marketplace.nvidia.com/de-de/consumer/graphics-cards/nvidia-geforce-rtx-5080/"
rtx_5090 = "https://marketplace.nvidia.com/de-de/consumer/graphics-cards/nvidia-geforce-rtx-5090/"
