# NVIDIA API Configuration

# FE inventory API URL for checking product availability
fe_inventory_url = "https://api.store.nvidia.com/partner/v1/feinventory?status=1&skus=PROFESHOP5090&locale=DE"

# Request settings
[request]
timeout_secs = 30 # API request timeout in seconds
max_attempts = 4 # max number of attempts to make the request
sleep_ms_min = 1000 # min time between requests in ms
sleep_ms_max = 1100 # max time between requests in ms

# Browser emulation headers
[headers]
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
accept = "application/json, text/plain, */*"
accept_language = "en-US,en;q=0.9,de;q=0.8"
connection = "keep-alive"
cache_control = "no-cache"
pragma = "no-cache"
sec_fetch_dest = "empty"
sec_fetch_mode = "cors"
sec_fetch_site = "cross-site"
origin = "https://www.nvidia.com"
referer = "https://www.nvidia.com/"
sec_ch_ua = "\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\""
sec_ch_ua_mobile = "?0"
sec_ch_ua_platform = "\"Windows\""

# Purchase settings
[purchase]
enabled = true # Whether to attempt purchases when products are available
# List of product names to purchase when available
product_names = [
    "GeForce RTX 5070",
    "GeForce RTX 5080",
    "GeForce RTX 5090"
]
